version: '3.8'

services:
    nestjs: 
        container_name: main
        build:
            context: .
            target: development
        volumes:
            - .:/usr/src/app
            - /usr/src/app/node_modules
        ports:
            -${SERVER_PORT}:${SERVER_PORT}
    caddy:
    postgres: