version: '3.8'

services:
    main: 
        container_name: main
        build:
            context: .
            target: development
        volumes:
            - .:/usr/src/app
            - /usr/src/app/node_modules
        ports:
            -${SERVER_PORT}